version: "3.8"
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dong_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "9909:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8085:80"
    depends_on:
      - db
